# Generated by Django 4.2.16 on 2024-10-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name_of_company",
            field=models.CharField(max_length=100),
        ),
    ]
