# Generated by Django 4.2.16 on 2024-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_company_name_of_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee", name="emp_id", field=models.IntegerField(),
        ),
    ]
